version: 0.2

# for info on the build phases used here:
#   http://docs.aws.amazon.com/codebuild/latest/userguide/view-build-details.html#view-build-details-phases

# for info on the buildspec.yml syntax:
#   http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  variables:
    REPO: "ncm-cli"

phases:
  install:
    commands:
      - npm install
      - chmod +x tools/check-deps.sh

  build:
    commands:
      - npm run test
      - npm run check-deps
